// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Adesivo {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    nome: string;
    insta: string;
    imagens: { data: Media[] };
    video?: { data: Media };
    dificuldade?: number;
    criatividade?: number;
    visibilidade?: number;
    validado?: boolean;
    anonimo?: boolean;
    feedback?: string;
  };
}
export interface Adesivo_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  nome: string;
  insta: string;
  imagens: Media_Plain[];
  video?: Media_Plain;
  dificuldade?: number;
  criatividade?: number;
  visibilidade?: number;
  validado?: boolean;
  anonimo?: boolean;
  feedback?: string;
}

export interface Adesivo_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  nome: string;
  insta: string;
  imagens: number[];
  video?: number;
  dificuldade?: number;
  criatividade?: number;
  visibilidade?: number;
  validado?: boolean;
  anonimo?: boolean;
  feedback?: string;
}

export interface Adesivo_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  nome: string;
  insta: string;
  imagens: AdminPanelRelationPropertyModification<Media_Plain>[];
  video?: AdminPanelRelationPropertyModification<Media_Plain>;
  dificuldade?: number;
  criatividade?: number;
  visibilidade?: number;
  validado?: boolean;
  anonimo?: boolean;
  feedback?: string;
}
