// Interface automatically generated by schemas-to-ts

import { Produto } from './produto';
import { Lookbook } from './lookbook';
import { Loja } from './loja';
import { Produto_Plain } from './produto';
import { Lookbook_Plain } from './lookbook';
import { Loja_Plain } from './loja';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Drop {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    nome: string;
    cor?: string;
    produtos: { data: Produto[] };
    lookbook?: { data: Lookbook };
    loja?: { data: Loja };
    data?: Date;
    slug?: string;
  };
}
export interface Drop_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  nome: string;
  cor?: string;
  produtos: Produto_Plain[];
  lookbook?: Lookbook_Plain;
  loja?: Loja_Plain;
  data?: Date;
  slug?: string;
}

export interface Drop_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  nome: string;
  cor?: string;
  produtos: number[];
  lookbook?: number;
  loja?: number;
  data?: Date;
  slug?: string;
}

export interface Drop_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  nome: string;
  cor?: string;
  produtos: AdminPanelRelationPropertyModification<Produto_Plain>;
  lookbook?: AdminPanelRelationPropertyModification<Lookbook_Plain>;
  loja?: AdminPanelRelationPropertyModification<Loja_Plain>;
  data?: Date;
  slug?: string;
}
