// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Seo } from '../components/shared/Seo';
import { Media_Plain } from '../common/Media';
import { Seo_Plain } from '../components/shared/Seo';
import { Seo_NoRelations } from '../components/shared/Seo';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Home {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    manutencao?: boolean;
    imagens?: { data: Media[] };
    anuncios?: any;
    data_lancamento?: Date;
    texto_manutencao?: string;
    seo?: Seo;
  };
}
export interface Home_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  manutencao?: boolean;
  imagens?: Media_Plain[];
  anuncios?: any;
  data_lancamento?: Date;
  texto_manutencao?: string;
  seo?: Seo_Plain;
}

export interface Home_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  manutencao?: boolean;
  imagens?: number[];
  anuncios?: any;
  data_lancamento?: Date;
  texto_manutencao?: string;
  seo?: Seo_NoRelations;
}

export interface Home_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  manutencao?: boolean;
  imagens?: AdminPanelRelationPropertyModification<Media_Plain>[];
  anuncios?: any;
  data_lancamento?: Date;
  texto_manutencao?: string;
  seo?: Seo_Plain;
}
