// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Drop } from './drop';
import { Produto } from './produto';
import { Media_Plain } from '../common/Media';
import { Drop_Plain } from './drop';
import { Produto_Plain } from './produto';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Loja {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    title: string;
    slug?: string;
    logo?: { data: Media };
    cor?: string;
    whatsapp?: string;
    taxa?: number;
    drops: { data: Drop[] };
    produtos: { data: Produto[] };
  };
}
export interface Loja_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  title: string;
  slug?: string;
  logo?: Media_Plain;
  cor?: string;
  whatsapp?: string;
  taxa?: number;
  drops: Drop_Plain[];
  produtos: Produto_Plain[];
}

export interface Loja_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  title: string;
  slug?: string;
  logo?: number;
  cor?: string;
  whatsapp?: string;
  taxa?: number;
  drops: number[];
  produtos: number[];
}

export interface Loja_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  title: string;
  slug?: string;
  logo?: AdminPanelRelationPropertyModification<Media_Plain>;
  cor?: string;
  whatsapp?: string;
  taxa?: number;
  drops: AdminPanelRelationPropertyModification<Drop_Plain>;
  produtos: AdminPanelRelationPropertyModification<Produto_Plain>;
}
