// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Drop } from './drop';
import { Media_Plain } from '../common/Media';
import { Drop_Plain } from './drop';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Lookbook {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    capa: { data: Media };
    drop?: { data: Drop };
    fotos?: { data: Media[] };
  };
}
export interface Lookbook_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  capa: Media_Plain;
  drop?: Drop_Plain;
  fotos?: Media_Plain[];
}

export interface Lookbook_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  capa: number;
  drop?: number;
  fotos?: number[];
}

export interface Lookbook_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  capa: AdminPanelRelationPropertyModification<Media_Plain>;
  drop?: AdminPanelRelationPropertyModification<Drop_Plain>;
  fotos?: AdminPanelRelationPropertyModification<Media_Plain>[];
}
