// Interface automatically generated by schemas-to-ts

import { Produto } from './produto';
import { Media } from '../common/Media';
import { Produto_Plain } from './produto';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Pacote {
  id: number;
  attributes: {
    createdAt: Date; updatedAt: Date; publishedAt?: Date; _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    nome: string;
    desconto?: number;
    produtos: { data: Produto[] };
    capa?: { data: Media };
  };
}
export interface Pacote_Plain {
  id: number;
  createdAt: Date; updatedAt: Date; publishedAt?: Date; _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  nome: string;
  desconto?: number;
  produtos: Produto_Plain[];
  capa?: Media_Plain;
}

export interface Pacote_NoRelations {
  id: number;
  createdAt: Date; updatedAt: Date; publishedAt?: Date; _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  nome: string;
  desconto?: number;
  produtos: number[];
  capa?: number;
}

export interface Pacote_AdminPanelLifeCycle {
  id: number;
  createdAt: Date; updatedAt: Date; publishedAt?: Date; _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  nome: string;
  desconto?: number;
  produtos: AdminPanelRelationPropertyModification<Produto_Plain>;
  capa?: AdminPanelRelationPropertyModification<Media_Plain>;
}
