// Interface automatically generated by schemas-to-ts

import { Produto } from './produto';
import { Produto_Plain } from './produto';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Pacote {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    nome: string;
    desconto?: number;
    produtos: { data: Produto[] };
  };
}
export interface Pacote_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  nome: string;
  desconto?: number;
  produtos: Produto_Plain[];
}

export interface Pacote_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  nome: string;
  desconto?: number;
  produtos: number[];
}

export interface Pacote_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  nome: string;
  desconto?: number;
  produtos: AdminPanelRelationPropertyModification<Produto_Plain>;
}
