// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Drop } from './drop';
import { Variante } from '../components/produto/Variante';
import { Loja } from './loja';
import { Media_Plain } from '../common/Media';
import { Drop_Plain } from './drop';
import { Variante_Plain } from '../components/produto/Variante';
import { Loja_Plain } from './loja';
import { Variante_NoRelations } from '../components/produto/Variante';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export enum Tipo {
  Camiseta = 'Camiseta',
  Camisa = 'Camisa',
  Cinto = 'Cinto',
  Colete = 'Colete',
  Polo = 'Polo',
  Bone = 'Boné',
  CalcA = 'Calça',
  Short = 'Short',
  Bermuda = 'Bermuda',
  Jaqueta = 'Jaqueta',
  SueTer = 'Suéter',
  MacacaO = 'Macacão',
  Casaco = 'Casaco',
  OCulos = 'Óculos',
  ReloGio = 'Relógio',
  ShoulderBag = 'Shoulder Bag',
  TeNis = 'Tênis',
  Pulseira = 'Pulseira',}

export interface Produto {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    title: string;
    slug?: string;
    tipo: Tipo;
    imagens_produto?: { data: Media[] };
    drop?: { data: Drop };
    descricao?: string;
    categorias?: string[];
    variantes: Variante[];
    loja?: { data: Loja };
    usado: boolean;
    locale: string;
    localizations?: { data: Produto[] };
  };
}
export interface Produto_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  title: string;
  slug?: string;
  tipo: Tipo;
  imagens_produto?: Media_Plain[];
  drop?: Drop_Plain;
  descricao?: string;
  categorias?: string[];
  variantes: Variante_Plain[];
  loja?: Loja_Plain;
  usado: boolean;
  locale: string;
  localizations?: Produto_Plain[];
}

export interface Produto_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  title: string;
  slug?: string;
  tipo: Tipo;
  imagens_produto?: number[];
  drop?: number;
  descricao?: string;
  categorias?: string[];
  variantes: Variante_NoRelations[];
  loja?: number;
  usado: boolean;
  locale: string;
  localizations?: Produto[];
}

export interface Produto_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  title: string;
  slug?: string;
  tipo: Tipo;
  imagens_produto?: AdminPanelRelationPropertyModification<Media_Plain>[];
  drop?: AdminPanelRelationPropertyModification<Drop_Plain>;
  descricao?: string;
  categorias?: string[];
  variantes: Variante_Plain[];
  loja?: AdminPanelRelationPropertyModification<Loja_Plain>;
  usado: boolean;
  locale: string;
  localizations?: Produto[];
}
