// Interface automatically generated by schemas-to-ts

import { Cliente } from './cliente';
import { Produto } from './produto';
import { Cliente_Plain } from './cliente';
import { Produto_Plain } from './produto';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export enum TipoEntrega {
  Retirada = 'retirada',
  Entrega = 'entrega',}
export enum LocalRetirada {
  UnB = 'UnB',
  RodoviaRia = 'Rodoviária',
  GuaraIi = 'Guará II',
  AsaNorte = 'Asa Norte',
  Paranoa = 'Paranoá',}
export enum TipoPagamento {
  Credit = 'credit',
  Pix = 'pix',}

export interface Venda {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    feedback?: string;
    cliente?: { data: Cliente };
    produtos: { data: Produto[] };
    tipo_entrega?: TipoEntrega;
    local_retirada?: LocalRetirada;
    id_kangu?: string;
    tipo_pagamento?: TipoPagamento;
    subtotal?: number;
    frete?: number;
    total?: number;
    id_pagamento?: string;
    parcelas?: number;
    descricao?: string;
  };
}
export interface Venda_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  feedback?: string;
  cliente?: Cliente_Plain;
  produtos: Produto_Plain[];
  tipo_entrega?: TipoEntrega;
  local_retirada?: LocalRetirada;
  id_kangu?: string;
  tipo_pagamento?: TipoPagamento;
  subtotal?: number;
  frete?: number;
  total?: number;
  id_pagamento?: string;
  parcelas?: number;
  descricao?: string;
}

export interface Venda_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  feedback?: string;
  cliente?: number;
  produtos: number[];
  tipo_entrega?: TipoEntrega;
  local_retirada?: LocalRetirada;
  id_kangu?: string;
  tipo_pagamento?: TipoPagamento;
  subtotal?: number;
  frete?: number;
  total?: number;
  id_pagamento?: string;
  parcelas?: number;
  descricao?: string;
}

export interface Venda_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  feedback?: string;
  cliente?: AdminPanelRelationPropertyModification<Cliente_Plain>;
  produtos: AdminPanelRelationPropertyModification<Produto_Plain>;
  tipo_entrega?: TipoEntrega;
  local_retirada?: LocalRetirada;
  id_kangu?: string;
  tipo_pagamento?: TipoPagamento;
  subtotal?: number;
  frete?: number;
  total?: number;
  id_pagamento?: string;
  parcelas?: number;
  descricao?: string;
}
