// Interface automatically generated by schemas-to-ts

import { Produto } from './produto';
import { Produto_Plain } from './produto';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Venda {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    _softDeletedAt?: Date;
    _softDeletedById?: number;
    _softDeletedByType?: string;
    nome: string;
    insta?: string;
    data?: Date;
    cpf?: string;
    observations?: string;
    produtos: { data: Produto[] };
    email?: string;
    celular?: string;
  };
}
export interface Venda_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  nome: string;
  insta?: string;
  data?: Date;
  cpf?: string;
  observations?: string;
  produtos: Produto_Plain[];
  email?: string;
  celular?: string;
}

export interface Venda_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  nome: string;
  insta?: string;
  data?: Date;
  cpf?: string;
  observations?: string;
  produtos: number[];
  email?: string;
  celular?: string;
}

export interface Venda_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  _softDeletedAt?: Date;
  _softDeletedById?: number;
  _softDeletedByType?: string;
  nome: string;
  insta?: string;
  data?: Date;
  cpf?: string;
  observations?: string;
  produtos: AdminPanelRelationPropertyModification<Produto_Plain>;
  email?: string;
  celular?: string;
}
