import localFont from 'next/font/local'

const clash = localFont({ src: '../assets/fonts/ClashDisplay-Variable.ttf' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clash.className}>{children}</body>
    </html>
  )
}
