export const deliveryLocations = [{ local: 'Plano (Asa Norte, Asa Sul, Cruzeiro, Sudoeste)',tax: 4 },{ local: 'Guará I',tax: 4 },{ local: 'Guará II',tax: 4 },{ local: 'Taguatinga',tax: 6 },{ local: 'Núcleo Bandeirante',tax: 5 },{ local: 'Vicente Pires',tax: 6 },{ local: 'Candangolândia',tax: 5.50 },{ local: 'Park Way',tax: 7 },{ local: 'Arniqueiras',tax: 7 },{ local: 'Lago Sul',tax: 8 },{ local: 'Paranoá',tax: 4 },{ local: 'Itapoã',tax: 4.50 },{ local: 'Lago Norte',tax: 6},{ local: 'Riacho Fundo 1',tax: 6}]

export const pickupLocations = ['UnB','Rodoviária','Guará II','Asa Norte','Paranoá']

export const questions = [
  { title: "E pra pagar, como faz?",text: "É simples! Aceitamos Pix, Cartão de Crédito e Dinheiro! Mandaremos todas as informações certinho pelo zap. Se quiser pagar no crédito, é só selecionar a opção e preencher todos os dados! No caso do dinheiro, é só falar se vai precisar de troco e faremos a entrega tipo moto boy 😎." },
  { title: "E como eu vou receber a roupa?",text: "Você que escolhe! Se você olhar ali em cima tem todas as informações pra retirada ou entrega das peças. Se tiver qualquer outra dúvida a gnt explica tudo no nosso zap ou no insta (@ruadebaixoloja)" },
  { title: "E se eu me arrepender da compra?",text: "Duvido! Brincadeira, não existe problema algum! É só entrar em contato no nosso zap ou na DM do insta que a gnt desenrola tudo bem certinho!" },
  // { title: "Como funciona isso de falar o preço que eu quero pagar?",text: "É bem simples! Você seleciona o valor que quer pagar na barra de preço, daí a gente  vai negociando pelo zap! Quem sabe a gente não faz um combo daora com o preço melhor ainda? Nós aqui da Rua De Baixo, como bons brasileiros, adoramos a possibilidade de negociar de uma forma que todo mundo saia no lucro! É claro, todo esse processo leva um tempo e é possível que a peça que você deseja seja vendida! Então, não perca tempo!" },
  { title: "Como eu posso falar diretamente com vocês?",text: "É só chamar a gnt no nosso insta @ruadebaixoloja ou dar um salvao no zap (numero do zap) a gnt vai fazer de tudo pra responder o mais rápido possível" },
  { title: "Quem são vocês?",text: "Somos jovens universitários que entregamos a moda das ruas para o povo. Gostamos de Rap, skate, bmx e moda. Percebemos que podemos mostrar uma versão muito única do que vivemos nas ruas de Brasília. Como? mostrando nosso estilo de vida e entregando as melhores peças de roupas possíveis. Como vocês conseguem as roupas? No momento, trabalhamos na modalidade ‘’brechó’’, isso significa que pegamos, em sua maioria, roupas de 2a mão, tratamos (tiramos manchas, limpamos, remendamos), e vendemos!" },
  { title: "Quando tem novidades?",text: "SEMPRE!  Nós atualizamos tudo lá no nosso insta!! @ruadebaixoloja" },
  { title: "As roupas são originais?",text: "Muitas sabemos que são originais e muito exclusivas. Mas, infelizmente, não podemos garantir já que são de 2a mão." }
]