export const ICONS = [
  { src: '/paint/star.webp', alt: 'Ícone Estrela' },
  { src: '/paint/rectangle-dotted.webp', alt: 'Ícone Retângulo Pontilhado' },
  { src: '/paint/eraser.webp', alt: 'Ícone Borracha' },
  { src: '/paint/bucket.webp', alt: 'Ícone Balde de Tinta' },
  { src: '/paint/drop.webp', alt: 'Ícone Gota' },
  { src: '/paint/magnify.webp', alt: 'Ícone Lupa' },
  { src: '/paint/pencil.webp', alt: 'Ícone Lápis' },
  { src: '/paint/brush.webp', alt: 'Ícone Pincel' },
  { src: '/paint/spray.webp', alt: 'Ícone Spray' },
  { src: '/paint/text.webp', alt: 'Ícone Texto' },
  { src: '/paint/line.webp', alt: 'Ícone Linha' },
  { src: '/paint/curve.webp', alt: 'Ícone Curva' },
  { src: '/paint/rectangle.webp', alt: 'Ícone Retângulo' },
  { src: '/paint/shape.webp', alt: 'Ícone Forma' },
  { src: '/paint/oval.webp', alt: 'Ícone Oval' },
  { src: '/paint/rounded.webp', alt: 'Ícone Retângulo Arredondado' },
]