const NEXT_PUBLIC_KANGU_API_URL = process.env.NEXT_PUBLIC_KANGU_API_URL;
const KANGU_API_TOKEN = process.env.KANGU_API_TOKEN;
const STRAPI_TOKEN = process.env.STRAPI_TOKEN;
const NEXT_PUBLIC_STRAPI_API_URL = process.env.NEXT_PUBLIC_STRAPI_API_URL;
const ZAP_API_TOKEN = process.env.ZAP_API_TOKEN;
const ZAP_URL = process.env.ZAP_URL;
const DISABLE_MAINTENANCE_MODE = process.env.DISABLE_MAINTENANCE_MODE === 'true';

export { 
  NEXT_PUBLIC_KANGU_API_URL,
  KANGU_API_TOKEN,
  STRAPI_TOKEN,
  NEXT_PUBLIC_STRAPI_API_URL,
  ZAP_API_TOKEN,
  ZAP_URL,
  DISABLE_MAINTENANCE_MODE
};