// Interface automatically generated by schemas-to-ts

import { Media } from '../../common/Media';
import { Media_Plain } from '../../common/Media';

export interface ImagemUsando {
  imagem: { data: Media };
}
export interface ImagemUsando_Plain {
  imagem: Media_Plain;
}

export interface ImagemUsando_NoRelations {
  imagem: number;
}

