// Interface automatically generated by schemas-to-ts

export interface Variante {
  quantidade: number;
  tamanho: string;
  cor?: any;
  desconto: number;
  valor: number;
}
export interface Variante_Plain {
  quantidade: number;
  tamanho: string;
  cor?: any;
  desconto: number;
  valor: number;
}

export interface Variante_NoRelations {
  quantidade: number;
  tamanho: string;
  cor?: any;
  desconto: number;
  valor: number;
}

